language: python

os: linux
dist: focal  # for clang-format>=10 (https://packages.ubuntu.com/focal/clang-format)

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

addons:
  apt:
    packages:
      - clang-format

install:
  - pip install -e .
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script:
  - python -m flake8 c_formatter_42
  - python -m mypy c_formatter_42
  - python -m pytest c_formatter_42
